name: Auto Node Update
on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '更新了')"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify Files
      run: |
        echo "仓库文件列表:"
        ls -l
        echo "检查必要文件:"
        if [ ! -f GAll.txt ]; then
          echo "::error::缺少 GAll.txt"
          exit 1
        fi
        if [ ! -f AddIP.txt ]; then
          echo "::error::缺少 AddIP.txt"
          exit 1
        fi

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        sudo apt-get install -y jq

    - name: Execute Script
      run: |
        python dist/GH-AC-main.py
        cat node_stats.json  # 输出 node_stats.json 文件的内容，便于调试
        echo "STATS_JSON=$(cat node_stats.json | jq -c .)" >> $GITHUB_ENV

    - name: Commit Changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 输出 STATS_JSON 的内容，调试用
        echo "STATS_JSON: $STATS_JSON"

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
        
        # 读取统计信息
        timestamp=$(echo "$STATS_JSON" | jq -r '.timestamp')

        # 输出 timestamp，用于调试
        echo "Timestamp: $timestamp"

        # 提交每个文件
        echo "$STATS_JSON" | jq -r '.stats | keys_unsorted[]' | while read filename; do
          line_count=$(echo "$STATS_JSON" | jq -r ".stats.\"$filename\"")
          
          # 强制添加文件
          git add "$filename"
          
          # 生成提交信息
          commit_msg="更新 ${line_count} 个节点 (${timestamp})"
          
          # 允许空提交
          git commit -m "$commit_msg" --allow-empty
        done
        
        # 推送所有提交
        git push origin main
